### Importing Required Libraries

In [1]:
import pandas as pd

### Load Excel File

In [2]:

file_path = "../data/raw/Akwaaba_Insurance_Dataset.xlsx"
excel_file = pd.ExcelFile(file_path)
excel_file.sheet_names

['Corporate Clients',
 'Covered Employees',
 'Claims',
 'Policy Table',
 'Premium Payments',
 'Branch Table',
 'Claim Workflow',
 'Beneficiaries',
 'Risk Scores']

In [3]:
## Load all sheets
sheets = pd.read_excel(file_path, sheet_name=None)
sheets.keys()

dict_keys(['Corporate Clients', 'Covered Employees', 'Claims', 'Policy Table', 'Premium Payments', 'Branch Table', 'Claim Workflow', 'Beneficiaries', 'Risk Scores'])

### Data Profiling

In [4]:
### Check dataset sizes (first profiling signal)
for name, df in sheets.items():
    print(name, df.shape)

Corporate Clients (70, 10)
Covered Employees (1974, 10)
Claims (2500, 7)
Policy Table (70, 6)
Premium Payments (420, 6)
Branch Table (70, 3)
Claim Workflow (165, 6)
Beneficiaries (1974, 5)
Risk Scores (1974, 2)

### Analyze Covered Employees table

In [5]:
### Get the first 5 head of covered employees
df = sheets["Covered Employees"]
df.head()
df.head().to_string()

'  Employee_ID Corporate_ID        Employee_Name         Occupation Grade_Level  Monthly_Salary_GHS  Age  Gender  Dependents Smoker\n0    EMP00001      CORP001          April Perez   Network Engineer         Mid               12000   43    Male           2    Yes\n1    EMP00002      CORP001      Jonathan Morris  Software Engineer      Junior                8500   40  Female           4     No\n2    EMP00003      CORP001         Kathryn Cook   Network Engineer      Junior                7500   40    Male           4     No\n3    EMP00004      CORP001  Christopher Johnson  Software Engineer         Mid               13000   51  Female           0    Yes\n4    EMP00005      CORP001     Kenneth Thompson  Software Engineer      Junior                8500   58  Female           0     No'

In [6]:
### Get info on covered employee
df.info

<bound method DataFrame.info of      Employee_ID Corporate_ID        Employee_Name         Occupation  \
0       EMP00001      CORP001          April Perez   Network Engineer
1       EMP00002      CORP001      Jonathan Morris  Software Engineer
2       EMP00003      CORP001         Kathryn Cook   Network Engineer
3       EMP00004      CORP001  Christopher Johnson  Software Engineer
4       EMP00005      CORP001     Kenneth Thompson  Software Engineer
...          ...          ...                  ...                ...
1969    EMP01970      CORP070          Megan Jones  Software Engineer
1970    EMP01971      CORP070         Teresa Lopez  Software Engineer
1971    EMP01972      CORP070      Mr. Daniel Ross   Network Engineer
1972    EMP01973      CORP070            Roy Smith   Network Engineer
1973    EMP01974      CORP070        James Mendoza   Network Engineer

     Grade_Level  Monthly_Salary_GHS  Age  Gender  Dependents Smoker
0            Mid               12000   43    Male           2    Yes
1         Junior                8500   40  Female           4     No
2         Junior                7500   40    Male           4     No
3            Mid               13000   51  Female           0    Yes
4         Junior                8500   58  Female           0     No
...          ...                 ...  ...     ...         ...    ...
1969         Mid               13000   53    Male           4     No
1970      Senior               19000   53    Male           3    Yes
1971         Mid               12000   37  Female           0    Yes
1972      Senior               17000   33    Male           0    Yes
1973         Mid               12000   45  Female           1     No

[1974 rows x 10 columns]>

In [7]:
### null outputs
df.isnull().sum()
df.isnull().sum().to_string()

'Employee_ID           0\nCorporate_ID          0\nEmployee_Name         0\nOccupation            0\nGrade_Level           0\nMonthly_Salary_GHS    0\nAge                   0\nGender                0\nDependents            0\nSmoker                0'

### Analyze Claims Table

In [8]:
### Check first 5 heads of Claims Table
df = sheets['Claims']
df.head().to_string()

'   Claim_ID Employee_ID Corporate_ID       Claim_Type  Claim_Amount_GHS Claim_Status  Claim_Date\n0  CLM00001    EMP01950      CORP069  Funeral Benefit             15040     Approved  2024-09-24\n1  CLM00002    EMP00184      CORP007           Dental              7155     Rejected  2025-12-08\n2  CLM00003    EMP00706      CORP027  Funeral Benefit             15572      Pending  2025-03-07\n3  CLM00004    EMP01925      CORP069  Hospitalization             44381     Approved  2024-05-12\n4  CLM00005    EMP01390      CORP049   Emergency Care             14988      Pending  2024-07-28'

In [9]:
df = sheets['Claims']
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Claim_ID          2500 non-null   str
 1   Employee_ID       2500 non-null   str
 2   Corporate_ID      2500 non-null   str
 3   Claim_Type        2500 non-null   str
 4   Claim_Amount_GHS  2500 non-null   int64
 5   Claim_Status      2500 non-null   str
 6   Claim_Date        2500 non-null   str
dtypes: int64(1), str(6)
memory usage: 264.8 KB

In [10]:
df.isnull().sum().to_string()

'Claim_ID            0\nEmployee_ID         0\nCorporate_ID        0\nClaim_Type          0\nClaim_Amount_GHS    0\nClaim_Status        0\nClaim_Date          0'

### Analyze Premium Table

In [11]:
df = sheets["Premium Payments"]
df.head().to_string()

'  Payment_ID Corporate_ID Payment_Date  Amount_GHS Payment_Status     Payment_Method\n0   PAY00011      CORP001   2025-12-15       37200        Pending  Payroll Deduction\n1   PAY00012      CORP001   2026-01-15       37200           Paid      Bank Transfer\n2   PAY00013      CORP001   2026-02-15       37200           Paid  Payroll Deduction\n3   PAY00014      CORP001   2026-03-15       37200           Paid      Bank Transfer\n4   PAY00015      CORP001   2026-04-15       37200           Paid      Bank Transfer'

### Analyze Corporate Clients Table

In [12]:
df = sheets["Corporate Clients"]
df.head()

,Corporate_ID,Company_Name,Branch_ID,Industry,Region,Number_of_Staff,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,CORP001,MTN Ghana,BR001,Telecommunications,Accra,1800,Group Welfare Plan,248,HR Benefits,2025-11-15
1,CORP002,MTN Ghana,BR002,Telecommunications,Kumasi,250,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,CORP003,MTN Ghana,BR003,Telecommunications,Takoradi,120,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,CORP004,MTN Ghana,BR004,Telecommunications,Tamale,80,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,CORP005,MTN Ghana,BR005,Telecommunications,Ho,35,Group Life Insurance Plan,226,Employee Welfare,2024-03-06

### Analyze Branch Table

In [13]:
df = sheets["Branch Table"]
df.head()

  Branch_ID Company_Name    Region
0     BR001    MTN Ghana     Accra
1     BR002    MTN Ghana    Kumasi
2     BR003    MTN Ghana  Takoradi
3     BR004    MTN Ghana    Tamale
4     BR005    MTN Ghana        Ho

### Analyze or Check the Claim_Workflow Table

In [14]:
df = sheets["Claim Workflow"]
df.head()

,Workflow_ID,Claim_ID,Submitted_Date,Reviewed_Date,Approved_By,Payout_Date
0,WF00001,CLM00001,2025-01-23,2025-01-27,Abena Ofori,NaN
1,WF00002,CLM00002,2024-06-12,2024-06-24,Michael Owusu,2024-07-04
2,WF00003,CLM00003,2025-10-15,2025-10-19,Daniel Asare,NaN
3,WF00004,CLM00004,2024-07-25,2024-07-28,Abena Ofori,NaN
4,WF00005,CLM00005,2024-09-16,2024-09-20,Kwame Mensah,2024-09-24

### Analyze Beneficiaries Table

In [15]:
df = sheets["Beneficiaries"]
df.head().to_string()

'  Beneficiary_ID Employee_ID            Beneficiary_Name Relationship  Allocation_Percentage\n0       BEN00001    EMP00001          April Perez Family       Spouse                    100\n1       BEN00002    EMP00002      Jonathan Morris Family      Sibling                    100\n2       BEN00003    EMP00003         Kathryn Cook Family       Parent                    100\n3       BEN00004    EMP00004  Christopher Johnson Family      Sibling                    100\n4       BEN00005    EMP00005     Kenneth Thompson Family      Sibling                    100'

### Analyze Risk Scores Table

In [16]:
df = sheets["Risk Scores"]
df.head().to_string()

'    Risk_ID Employee_ID\n0  RSK00001    EMP00001\n1  RSK00002    EMP00002\n2  RSK00003    EMP00003\n3  RSK00004    EMP00004\n4  RSK00005    EMP00005'

### REAL DATA PROFILING SUMMARY

In [17]:
summary = {
    sheet: df.shape for sheet, df in sheets.items()
}

summary

{'Corporate Clients': (70, 10),
 'Covered Employees': (1974, 10),
 'Claims': (2500, 7),
 'Policy Table': (70, 6),
 'Premium Payments': (420, 6),
 'Branch Table': (70, 3),
 'Claim Workflow': (165, 6),
 'Beneficiaries': (1974, 5),
 'Risk Scores': (1974, 2)}

### ISSUES IDENTIFIED (IMPORTANT)

In [18]:
## 1. Data type problems
"""
Dates stored as strings:
Claim_Date
Payment_Date
Application_Date
Workflow dates
"""

## 2. Corporate Clients design issue
"""
Company duplicated across branches
Mixed company + branch logic
"""

## 3. Beneficiaries design concern
"""
Allocation always 100%
→ likely oversimplified or incomplete modeling
"""  

## 4. Risk Scores table incomplete
"""
No actual score values
→ needs full feature engineering later
""" 

## 5. Workflow table risk
"""
Missing Payout_Date values
→ expected but must be validated later for process analysis
"""

'\nMissing Payout_Date values\n→ expected but must be validated later for process analysis\n'